---
# tasks file for roles/ubuntu-user-docker
- name: Creating docker group
  group:
    name: docker
    state: present

- name: Add docker group to current user
  user:
    name: gerald-tip
    group: docker
